from . import teaching_config
from . import res_partner
from . import appointment_type
from . import calendar_event
from . import teaching_course
from . import account_move
from . import blog_post
from . import res_config_settings
from . import account_followup
