{
    'name': 'Teaching',
    'version': '19.0.1.0.1',
    'category': 'Services',
    'summary': 'Sigma Academy: sessions, availability, courses, billing and portal',
    'author': 'Al Shayeb Auditing and Accountancy Co',
    'license': 'OEEL-1',
    'depends': [
        'contacts',
        'hr',
        'account',
        'website_blog',
        'appointment',
        'website_appointment',
        'appointment_google_calendar',
        'whatsapp_calendar',
        'account_followup',
        'whatsapp_account_followup',
    ],
    'data': [
        'security/teaching_security.xml',
        'security/ir.model.access.csv',
        'data/teaching_data.xml',
        'data/mail_templates.xml',
        'views/teaching_config_views.xml',
        'views/res_partner_views.xml',
        'views/appointment_type_views.xml',
        'views/calendar_event_views.xml',
        'views/teaching_course_views.xml',
        'views/account_move_views.xml',
        'views/blog_post_views.xml',
        'views/res_config_settings_views.xml',
        'wizards/teaching_wizard_views.xml',
        'views/menus.xml',
        'views/appointment_templates.xml',
        'views/portal_templates.xml',
    ],
    'application': True,
    'installable': True,
}
